version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    versioning-strategy: increase
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: chore(deps)
    groups:
      all-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - rust
    commit-message:
      prefix: chore(deps)
    groups:
      all-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major
